### ISSUE TITLE
score.txt file is not generated

### ISSUE THREAD

**Issue by joongsp** [rubis-lab/CPSim_linux#9]
After I stop the simulator, I cannot find 'score.txt' in 'eclipse' directory. I did 2 other environments. But the results were same. Can I know which part I need to check for this kind of issue?

**Comment by lamnd09** [comment]
Hi, maybe  Simulator/engine/real-time_simulator_basic.cpp is what you are looking for.

**Comment by we123456** [comment]
I cannot know why the score function does not operate correctly yet.
Thus, please calculate the score function manually.
You can do this with "distance.txt" and "lap_time.txt" files in eclipse directory.

**Comment by joongsp** [comment]
This issue is gone. I was using older version of simulator files which it doesn't have print score.txt. Many thanks @lamnd09 & @we123456.
